"""Generate supabase/migrations/0002_seed_airtable.sql from the 4 Airtable CSVs.

Parses the exported grids, dedupes natural keys, normalises money/date/time
values, resolves foreign keys (nulling unresolved ones), and emits idempotent
INSERTs. Run locally — needs no DB connection:

    python -m scripts.gen_seed_from_csv               # uses default CSV dir
    python -m scripts.gen_seed_from_csv "<csv_dir>"   # custom dir
"""

from __future__ import annotations

import csv
import re
import sys
import uuid
from pathlib import Path

CSV_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
    r"C:\Users\Hansen\Downloads\Vinci Automation Prompt Materials"
)
OUT = Path(__file__).resolve().parents[1].parent / "supabase" / "migrations" / "0002_seed_airtable.sql"

FILES = {
    "schools": "Schools-Grid view.csv",
    "teachers": "Teachers-Grid view.csv",
    "courses": "Courses-Grid view.csv",
    "lessons": "Lessons-Grid view.csv",
}


# --- value formatters ------------------------------------------------------
def s(v):
    """SQL string literal or NULL."""
    if v is None:
        return "NULL"
    v = str(v).strip()
    if v == "" or v.lower() == "nan":
        return "NULL"
    return "'" + v.replace("'", "''") + "'"


def num(v):
    if v is None:
        return "NULL"
    v = re.sub(r"[,$\s]", "", str(v)).strip()
    if v == "" or v.lower() == "nan":
        return "NULL"
    try:
        return str(float(v))
    except ValueError:
        return "NULL"


def integer(v):
    n = num(v)
    return "NULL" if n == "NULL" else str(int(float(n)))


def date_iso(v):
    if not v:
        return "NULL"
    v = str(v).strip()
    m = re.match(r"^(\d{1,2})/(\d{1,2})/(\d{4})$", v)
    if m:
        mo, d, y = m.groups()
        return f"'{y}-{int(mo):02d}-{int(d):02d}'"
    if re.match(r"^\d{4}-\d{2}-\d{2}", v):
        return f"'{v[:10]}'"
    return "NULL"


def time_24(v):
    if not v:
        return "NULL"
    v = str(v).strip()
    m = re.match(r"^(\d{1,2}):(\d{2})\s*([AaPp][Mm])?$", v)
    if not m:
        return "NULL"
    hh, mm, ap = int(m.group(1)), m.group(2), m.group(3)
    if ap:
        ap = ap.lower()
        if ap == "pm" and hh != 12:
            hh += 12
        if ap == "am" and hh == 12:
            hh = 0
    return f"'{hh:02d}:{mm}'"


def ts(v):
    if not v:
        return "NULL"
    v = str(v).strip()
    return s(v) if re.match(r"^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}", v) else "NULL"


def boolean(v):
    if v and str(v).strip().lower() in ("checked", "true", "yes", "1"):
        return "TRUE"
    return "NULL"


def phone(v):
    if not v:
        return "NULL"
    digits = re.sub(r"\D", "", str(v))
    return s(digits) if digits else "NULL"


def read(name):
    with open(CSV_DIR / FILES[name], encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def first_token(v):
    if not v:
        return None
    return str(v).split(",")[0].strip()


def tokens(v):
    if not v:
        return []
    return [t.strip() for t in str(v).split(",") if t.strip()]


# --- build ----------------------------------------------------------------
def main():
    out = []
    out.append("-- AUTO-GENERATED by scripts/gen_seed_from_csv.py — do not edit by hand.")
    out.append("-- Real Airtable data. Run AFTER 0001_phase1_schema.sql.\n")
    out.append("begin;")
    out.append("truncate table public.lesson_events, public.lesson_tutor_offers, "
               "public.lessons, public.courses, public.teachers, public.schools restart identity cascade;\n")

    # Schools (dedupe by school_id, skip blank)
    schools = {}
    for r in read("schools"):
        sid = (r.get("School ID") or "").strip()
        if sid and sid not in schools:
            schools[sid] = r
    out.append("insert into public.schools (school_id, school_name, tutor_availability_submissions, tutor_availability_slots) values")
    rows = [f"({s(sid)}, {s(r.get('School Name'))}, {s(r.get('Tutor Availability Submissions'))}, {s(r.get('Tutor Availability Slots'))})"
            for sid, r in schools.items()]
    out.append(",\n".join(rows) + ";\n")

    # Teachers (dedupe by teacher_id, skip blank)
    teachers = {}
    for r in read("teachers"):
        tid = (r.get("Teacher ID") or "").strip()
        if tid and tid not in teachers:
            teachers[tid] = r
    cols = ("teacher_id, teacher_name, email, whatsapp_number, status, availability_description, "
            "tutor_rate, ta_rate, active_status, hours_score, skill_score, reliability_score, "
            "sick_leave_count, reschedule_count, availability_slots, lessons_assigned_number, "
            "background, courses_can_teach, skill_matches, cv_link, last_score_updated, "
            "completed_teaching_hours, last_completed_lesson_date, inactivity_penalty_applied, score_last_updated")
    out.append(f"insert into public.teachers ({cols}) values")
    rows = []
    for tid, r in teachers.items():
        rows.append("(" + ", ".join([
            s(tid), s(r.get("Teacher Name")), s(r.get("Email")), phone(r.get("WhatsApp Number")),
            s(r.get("Status")), s(r.get("Availability (Description)")),
            num(r.get("Tutor Rate (HKD/hour)")), num(r.get("TA Rate (HKD/hour)")),
            integer(r.get("Active Status")), num(r.get("Hours Score")), num(r.get("Skill Score (Number)")),
            num(r.get("Reliability Score")), integer(r.get("Sick Leave Count")), integer(r.get("Reschedule Count")),
            integer(r.get("Availability Slots")), integer(r.get("Lessons Assigned Number")),
            s(r.get("Background")), s(r.get("Courses Can Teach")), s(r.get("Skill Matches")), s(r.get("CV Link")),
            ts(r.get("Last Score Updated")), num(r.get("Completed Teaching Hours (Scoring)")),
            date_iso(r.get("Last Completed Lesson Date (Scoring)")), boolean(r.get("Inactivity Penalty Applied")),
            ts(r.get("Score Last Updated")),
        ]) + ")")
    out.append(",\n".join(rows) + ";\n")

    # Courses
    courses = {}
    for r in read("courses"):
        cid = (r.get("Course ID") or "").strip()
        if cid and cid not in courses:
            courses[cid] = r
    out.append("insert into public.courses (course_id, course_name, school_id, course_topic, course_types, revenue_per_lesson, scheduled_classes_ai_summary) values")
    rows = []
    for cid, r in courses.items():
        sid = (r.get("School") or "").strip()
        rows.append("(" + ", ".join([
            s(cid), s(r.get("Course Name")), s(sid) if sid in schools else "NULL",
            s(r.get("Course Topic")), s(r.get("Course Types")),
            num(r.get("Revenue per Lesson")), s(r.get("Scheduled Classes AI Summary")),
        ]) + ")")
    out.append(",\n".join(rows) + ";\n")

    # Lessons (+ accepted offers)
    lesson_rows, offer_rows = [], []
    for r in read("lessons"):
        lid = str(uuid.uuid4())
        tid = first_token(r.get("Teacher"))
        teacher_sql = s(tid) if tid in teachers else "NULL"
        cid = first_token(r.get("Course"))
        course_sql = s(cid) if cid in courses else "NULL"
        lesson_rows.append("(" + ", ".join([
            f"'{lid}'", s(r.get("Lesson ID")), date_iso(r.get("Date")),
            time_24(r.get("Start time")), time_24(r.get("End time")),
            teacher_sql, course_sql, s(r.get("Status")), s(r.get("Role")),
            integer(r.get("Lesson Duration (minutes)")), num(r.get("Miscellaneous Expenses")),
            s(r.get("Tutor Assignment")), ts(r.get("Offer Sent Timestamp")),
            num(r.get("Lesson Income")),
        ]) + ")")
        for at in tokens(r.get("Teacher's Accepted")):
            if at in teachers:
                offer_rows.append(
                    f"('{lid}', {s(at)}, 'accepted', {ts(r.get('Offer Sent Timestamp'))}, 'Accepted (imported)')"
                )

    out.append("insert into public.lessons (id, lesson_id, date, start_time, end_time, teacher_id, course_id, "
               "status, role, lesson_duration_minutes, miscellaneous_expenses, tutor_assignment, offer_sent_timestamp, lesson_income) values")
    out.append(",\n".join(lesson_rows) + ";\n")

    if offer_rows:
        out.append("insert into public.lesson_tutor_offers (lesson_id, teacher_id, offer_status, responded_at, last_send_result) values")
        # de-dupe (lesson, teacher) pairs that repeat
        seen, uniq = set(), []
        for row in offer_rows:
            key = row.split(",")[0] + row.split(",")[1]
            if key not in seen:
                seen.add(key)
                uniq.append(row)
        out.append(",\n".join(uniq) + "\non conflict (lesson_id, teacher_id) do nothing;\n")

    out.append("commit;")
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  schools={len(schools)}  teachers={len(teachers)}  courses={len(courses)}  "
          f"lessons={len(lesson_rows)}  accepted_offers={len(offer_rows)}")


if __name__ == "__main__":
    main()
